name: 1.0.$(Rev:r)
pool:
  vmImage: ubuntu-latest

variables:
  - group: LITTLENUNNASPIZZA_AWS_CDK
  - name: npm_config_cache_app
    value: $(Pipeline.Workspace)/app/.npm
  - name: npm_config_cache_cdk
    value: $(Pipeline.Workspace)/cdk/.npm

stages:
  - stage: Build
    displayName: Build ui, api and cdk
    jobs:
      - job: Build
        steps:
        
          - powershell: |
              # Get the commits for the pull request
              $commitsUrl = "$(System.CollectionUri)$(System.TeamProject)/_apis/git/repositories/$(Build.Repository.Name)/pullRequests/$(System.PullRequest.PullRequestId)/commits?api-version=7.1"
              echo $commitsUrl
              $commitsResponse = Invoke-RestMethod -Uri $commitsUrl -Method Get  -Headers @{Authorization = "Bearer $env:SYSTEM_ACCESSTOKEN"}
              # Extract and print the commit messages
              $commitMessages = $commitsResponse.value.comment
              $commitMessages
              Write-Host "##vso[task.setvariable variable=Pr.Title]$commitMessages"
              env:
                SYSTEM_ACCESSTOKEN: $(system.accesstoken)
              displayName: 'Get Pull Request Commit Messages'

          - script: echo $(Pr.Title)
            displayName: PR Title

          # set environment name to git commit id to be used in next script
          - script: echo "##vso[task.setvariable variable=PR_ENVIRONMENT_NAME]${BUILD_SOURCEVERSION::5}"
            displayName: set environment name

          # echo environment name
          - script: echo $(PR_ENVIRONMENT_NAME)
            displayName: PR environment name
                      
          # will create env if commit message has [env] in it
          - script: echo "Will create environment for $(PR_ENVIRONMENT_NAME)"
            displayName: create environment
            condition: |
              contains(variables['Pr.Title'], '[env]')

          # if commit message does not have [env] in it, it will say this message
          - script: echo "Will not create environment for $(PR_ENVIRONMENT_NAME)"
            displayName: do not create environment
            condition: |
              not(contains(variables['Pr.Title'], '[env]'))

          - task: UseDotNet@2
            displayName: "Use .NET Core sdk"
            inputs:
              packageType: sdk
              version: 8.x
              installationPath: $(Agent.ToolsDirectory)/dotnet

          - script: dotnet publish --configuration "Release" /p:GenerateRuntimeConfigurationFiles=true /p:AssemblyVersion=$(Build.BuildNumber) --runtime linux-x64 --self-contained false
            displayName: "Build .net api"
            workingDirectory: src/api/src/Web

          - script: dotnet --version > ../app/src/versions/dotnet-version.txt
            displayName: "Get .NET version"
            workingDirectory: src/api

          - task: NodeTool@0
            inputs:
              versionSpec: "20.x"
            displayName: "Install NodeJS v20"
          - task: Cache@2
            inputs:
              key: "src/app/package-lock.json"
              path: $(npm_config_cache_app)
            displayName: Cache UI NPM packages
          - script: npm ci --cache $(npm_config_cache_app)
            workingDirectory: src/app
            displayName: "Install npm modules"

          - script: npm run build
            displayName: "Build UI"
            workingDirectory: src/app

          - task: Cache@2
            inputs:
              key: "src/cdk/package-lock.json"
              path: $(npm_config_cache_cdk)
            displayName: Cache CDK NPM packages
          - script: npm ci --cache $(npm_config_cache_cdk)
            displayName: install npm modules for cdk
            workingDirectory: src/cdk

          - script: sudo npm install -g aws-cdk
            displayName: install aws cdk

          - script: npm run cdk synth -- --context PR_ENVIRONMENT_NAME=$(PR_ENVIRONMENT_NAME) --context cloudfront-certificate-identifier=$(CDK_CLOUD_FRONT_CERTIFICATE_IDENTIFIER) --context hosted-zone-id=$(CDK_HOSTED_ZONE_ID)
            displayName: cdk synth
            workingDirectory: src/cdk

          - task: AmazonWebServices.aws-vsts-tools.AWSShellScript.AWSShellScript@1
            displayName: "Deploy CDK PR environment"
            inputs:
              awsCredentials: "azure-deployment"
              regionName: "eu-west-2"
              scriptType: "inline"
              workingDirectory: src/cdk
              inlineScript: cdk deploy --app '$(System.DefaultWorkingDirectory)/src/cdk/cdk.out' nunnaspizza-$(PR_ENVIRONMENT_NAME) --context PR_ENVIRONMENT_NAME=$(PR_ENVIRONMENT_NAME) --require-approval never --force --context cloudfront-certificate-identifier=$(CDK_CLOUD_FRONT_CERTIFICATE_IDENTIFIER) --context hosted-zone-id=$(CDK_HOSTED_ZONE_ID)
            condition: |
              contains(variables['Pr.Title'], '[env]')

          - publish: $(System.DefaultWorkingDirectory)/src/cdk/cdk.out
            artifact: build
